### ISSUE TITLE
🐛 `RepetitionTime` missing from `scan_parameters`

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/app-C-PAC-brainlife.io#6]
**Describe the bug**

`aCompCor_tr_string2float` & `tCompCor_tr_string2float` both complain
```Python
Node inputs:
function_str = def TR_string_to_float(tr):
    if 'ms' in tr:
        tr = float(tr.replace('ms',''))/1000
    else:
        tr = float(tr.replace('s',''))
    return tr
tr = None
Traceback: 
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
    out = function_handle(**args)
  File "<string>", line 2, in TR_string_to_float
TypeError: argument of type 'NoneType' is not iterable
```

**To Reproduce**
1. Go to [C-PAC on brainlife.io](https://brainlife.io/app/5f3593e84615e04651bf9364)
2. Choose a subject (anat & func)
3. Set `preconfig` to `fmriprep-options`

**Expected behavior**

TR should be known and set.

**Versions** 
 - C-PAC: 1.7.1
 - Container Platform :
    - Singularity
 - SLURM
 - app-C-PAC-brainlife.io: 0.0.0-dev
    

**Additional context**

I'm not sure whether https://github.com/FCP-INDI/app-C-PAC-brainlife.io/blob/c2fb306fb9d42cb69a803e9d1eec65fdf3d818c7/main#L28 should be doing something to get the repetition time metadata or if C-PAC itself should.

Run log: https://github.com/FCP-INDI/cpac_run_logs/issues/3

**Comment by shnizzedy** [comment]
Resolved in https://github.com/FCP-INDI/C-PAC/pull/1878 (C-PAC v1.8.6)
